// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwLHpYDUc61AnZEZLZ5_yv4_D1GiIaSMk',
    appId: '1:1098906626811:web:483d4b49f90b82717c5e5e',
    messagingSenderId: '1098906626811',
    projectId: 'follow-up-8c662',
    authDomain: 'follow-up-8c662.firebaseapp.com',
    storageBucket: 'follow-up-8c662.firebasestorage.app',
    measurementId: 'G-2HT3PQ4B2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALirdbowjHhb7OQRWemKeXj8nE701LHRw',
    appId: '1:1098906626811:android:bac14e63a51cbc0b7c5e5e',
    messagingSenderId: '1098906626811',
    projectId: 'follow-up-8c662',
    storageBucket: 'follow-up-8c662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCBsbK_I7Tqy-HNxkmHhxmSl4zXNIt55Q',
    appId: '1:1098906626811:ios:1da25a6b7c028f4b7c5e5e',
    messagingSenderId: '1098906626811',
    projectId: 'follow-up-8c662',
    storageBucket: 'follow-up-8c662.firebasestorage.app',
    iosBundleId: 'com.example.followupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCBsbK_I7Tqy-HNxkmHhxmSl4zXNIt55Q',
    appId: '1:1098906626811:ios:1da25a6b7c028f4b7c5e5e',
    messagingSenderId: '1098906626811',
    projectId: 'follow-up-8c662',
    storageBucket: 'follow-up-8c662.firebasestorage.app',
    iosBundleId: 'com.example.followupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASK1LpXC3Mlfm6_IdnVPvc52bo0uODGPo',
    appId: '1:1098906626811:web:d60ddfe90694b3267c5e5e',
    messagingSenderId: '1098906626811',
    projectId: 'follow-up-8c662',
    authDomain: 'follow-up-8c662.firebaseapp.com',
    storageBucket: 'follow-up-8c662.firebasestorage.app',
    measurementId: 'G-0R0MNFYNWQ',
  );
}
